### ISSUE TITLE
Remove old & unused Angular modules

### ISSUE THREAD

**Issue by MichaelBailly** [linagora/esn-frontend-common-libs#15]
Here is the list of AngularJs modules we want to remove:

```
frontend/js/modules/activitystream.js frontend/js/modules/activitystream/* frontend/js/modules/activitystreams-tracker.js
frontend/js/modules/easyrtc.js
frontend/js/modules/feedback.js
frontend/js/modules/like.js
frontend/js/modules/message.js
frontend/js/modules/poll.js
frontend/js/modules/resource-link.js
frontend/js/modules/twitter.js
frontend/js/modules/follow
frontend/js/modules/invitation.js
modules/linagora.esn.signup
modules/linagora.esn.signup.local
modules/linagora.esn.contact.import.twitter
modules/linagora.esn.digest.daily
```

For each of those modules:

1. check that no code path is depending on them
2. remove them if no code path is depending on them

Warning: there is activitystream related routing in `src/frontend/js/esn/app.js`.

**Comment by chamerling** [comment]
Note: If we did the job correctly in #8 and #9, removing the files/folders will throw a webpack error if they are required somewhere.

**Comment by asmaNode** [comment]
- This list of modules does not exist :(maybe was deleted)

frontend/js/modules/easyrtc.js

modules/linagora.esn.signup
modules/linagora.esn.signup.local
modules/linagora.esn.contact.import.twitter
modules/linagora.esn.digest.daily


- This list of modules has code depending on  them:

frontend/js/modules/activitystreams-tracker.js ( depends on sidebar.js)
frontend/js/modules/like.js (depends on resource-link)
frontend/js/modules/message.js (depends on timeline , like , resource-link)
