### ISSUE TITLE
As a devops I want to be able to use run time configuration

### ISSUE THREAD

**Issue by fabienmoyon** [linagora/esn-frontend-common-libs#193]
#### CURRENTLY 

For now at the run time ,we support to configure the `AUTH_PROVIDER_SETTINGS` in to the `openpaas.js`.

#### GOAL 

The goal is to able to use run time configuration 

#### EXPECTED 

Like it was done for the `AUTH_PROVIDER_SETTINGS` we need also to have the `OPENPAAS_URL`, the `BASE_HREF` and the `APP_GRID_ITEMS` in to the `openpaas.js`

##### LINKS

https://github.com/OpenPaaS-Suite/esn-frontend-inbox/blob/f96115397f368dc7b71101ba0bbf2fefe31d1c18/webpack.commons.js

https://github.com/OpenPaaS-Suite/esn-frontend-common-libs/blob/1131687b39fb989a5b41fafac2b5c8e99ac50cda/src/frontend/js/modules/auth/client.js
maintenant

https://github.com/OpenPaaS-Suite/openpaas-front

**Comment by tanandy** [comment]
ex: 

```
window.openpaas = {
  //AUTH_PROVIDER: 'basic'
  AUTH_PROVIDER: 'oidc',
  OPENPAAS_URL: 'http://backend.open-paas.org.local',
  BASE_HREF: '/inbox/',
  APP_GRID_ITEMS: '[{ "name": "Calendar", "url": "/calendar/" }, { "name": "Contacts", "url": "/contacts/" }, { "name": "Inbox", "url": "/inbox/" }]',
  AUTH_PROVIDER_SETTINGS: {
  authority: 'http://auth.open-paas.org.local/auth/realms/master',
  client_id: 'openpaas',
  redirect_uri: 'http://inbox.open-paas.org.local/inbox/#/auth/oidc/callback',
  silent_redirect_uri: 'http://inbox.open-paas.org.local/inbox/auth/silent-renew.html',
  post_logout_redirect_uri: 'http://inbox.open-paas.org.local/',
  response_type: 'code',
  scope: 'openid email profile'
  }
};
```

**Comment by alagane** [comment]
There is a webpack plugin to solve the BASE_HREF (publicPath on webpack) problem.
https://www.npmjs.com/package/webpack-dynamic-public-path
Since we use webpack ^4.43.0 this should be compatible.
We should test it to see if it solves the problem correctly.

**Comment by fabienmoyon** [comment]
ok so after investigation : 

1. `OPENPAAS_URL` will be rename by `API_BASE_URL` in to `openpaas.js` will be used to overload  [ESN restangular](https://github.com/OpenPaaS-Suite/esn-frontend-inbox/blob/a5db7e52e28c72dee52c0182478a393fcc4ecbfd/src/esn.inbox.libs/app/services/generate-jwt-token/generate-jwt-token.js#L10-L11)

1. `BASE_HREF` in to `openpaas.js`  will be used to overload [base(href=base)](https://github.com/OpenPaaS-Suite/esn-frontend-inbox/commit/3008461cb1d4886427bf8cf4f4fe0072b781f90d) [script(src="BASE_HREF/env/openpaas.js")](https://github.com/OpenPaaS-Suite/esn-frontend-inbox/blob/main/assets/index.pug#L42) and [inbox restangular](https://github.com/OpenPaaS-Suite/esn-frontend-inbox/commit/ca289d9efa6ab5e828d1f26af1b75b526717d098#diff-7b63b93ba5bae2ee0a317fe86536e8a262dc8963060657d92182e0f117e4740f)

@renaudboyer, @huy-ta @rezk2ll need also to be done in Calendar module and after done for others SPA (coutact, account and admin)

Second step need also to improve this workflow for [script(src="/socket.io/socket.io.js")](https://github.com/OpenPaaS-Suite/esn-frontend-inbox/blob/855a6ac42657823120962832534822cfa07570d4/assets/index.pug#L37)

@chamerling can you please have a look, told us if we don't miss something and validate what we want to do to be able to use run time configuration

**Comment by tanandy** [comment]
cc @huy-ta @rezk2ll @tuanlc @renaudboyer

**Comment by renaudboyer** [comment]
It's ok for the calendar team

**Comment by tanandy** [comment]
seems we can already use one variable to setup API BASE URL:

https://github.com/OpenPaaS-Suite/esn-frontend-common-libs/blob/1131687b39fb989a5b41fafac2b5c8e99ac50cda/src/frontend/js/modules/http.js#L102

**Comment by chamerling** [comment]
`OPENPAAS_API_URL` is already defined and must be used. Please update the doc and the `.env` samples

**Comment by tanandy** [comment]
cc @rezk2ll

**Comment by renaudboyer** [comment]
Static configuration done

Dynamic configuration will be dealt here: #237
