### ISSUE TITLE
fix the platform logo and avatar api endpoint

### ISSUE THREAD

**Issue by rezk2ll** [linagora/esn-frontend-common-libs#197]
should use the OPENPAAS_API_URL provided in the openpaas.js env file instead of the current location.

**Comment by rezk2ll** [comment]
should use the `OPENPAAS_API_URL` provided in the openpaas.js env file instead of the current location.

**Comment by fabienmoyon** [comment]
We sow yesterday that we also need to fix the `baseUrl` for the user api no ?

**Comment by rezk2ll** [comment]
> We sow yesterday that we also need to fix the `baseUrl` for the user api no ?

there is a lot more to fix
