### ISSUE TITLE
fix openpaas API calls error

### ISSUE THREAD

**Issue by rezk2ll** [linagora/esn-frontend-common-libs#200]
the error:
```
angular.js:11706 TypeError: Cannot read property 'protocol' of undefined
    at ar (angular.js:16550)
    at angular.js:9687
    at u (angular.js:9406)
    at angular.js:13318
    at angular.js:13334
    at d.$eval (angular.js:14570)
    at d.$digest (angular.js:14386)
    at d.$apply (angular.js:14675)
    at angular.js:9725
    at y (angular.js:9915)
```

**Comment by fabienmoyon** [comment]
Can you give us the context and when you get it to be able to reproduce and fix it

**Comment by rezk2ll** [comment]
> Can you give us the context and when you get it to be able to reproduce and fix it

after everything works fine with OIDC, the application stop at that error

**Comment by fabienmoyon** [comment]
this is due to a ui-router bug, INBOX no more redirect to /unifiedinbox/inbox by default, the issue is here https://github.com/linagora/esn-frontend-inbox/issues/280#issuecomment-781295043
