### ISSUE TITLE
Update old dependences links of openpaas-suite

### ISSUE THREAD

**Issue by fabienmoyon** [linagora/esn-frontend-common-libs#206]
We moved repositories from [openpaas-suite](https://github.com/openpaas-suite) to [linagora](https://github.com/linagora?type=source)

#### TO DO

We now need to update dependences links (package.json) of `openpaas-suite` to `linagora` repository. 

```
"dependencies": {    
    "esn-frontend-calendar": "github:openpaas-suite/esn-frontend-calendar#main",
    "esn-frontend-common-libs": "github:openpaas-suite/esn-frontend-common-libs#main",
    "esn-frontend-mailto-handler": "github:openpaas-suite/esn-frontend-mailto-handler#main",
    "esn-frontend-group": "github:openpaas-suite/esn-frontend-group#main",
    "esn-frontend-inbox-james": "github:openpaas-suite/esn-frontend-inbox-james#main",
    "esn-frontend-contacts": "github:openpaas-suite/esn-frontend-contacts#main"
    },
```

Need to done on all these repository : 

**libs**
- [x] [common-libs](https://github.com/linagora/esn-frontend-common-libs)
- [x] [esn-api-client](https://github.com/linagora/esn-api-client)
- [x] [esn-dav-import-client](https://github.com/linagora/esn-dav-import-client)
- [x] [openpaas-auth-client](https://github.com/linagora/openpaas-auth-client)

**frontend**
- [x] [inbox](https://github.com/linagora/esn-frontend-inbox)
- [x] [inbox-calendar](https://github.com/linagora/esn-frontend-inbox-calendar)
- [x] [inbox-linshare](https://github.com/linagora/esn-frontend-inbox-linshare)
- [x] [inbox-james](https://github.com/linagora/esn-frontend-inbox-james)
- [x] [mailto](https://github.com/linagora/esn-frontend-mailto)
- [x] [mailto-handler](https://github.com/linagora/esn-frontend-mailto-handler)
- [x] [calendar](https://github.com/linagora/esn-frontend-calendar)
- [x] [calendar-public](https://github.com/linagora/esn-frontend-calendar-public)
- [x] [contacts](https://github.com/linagora/esn-frontend-contacts)
- [x] [account](https://github.com/linagora/esn-frontend-account)
- [x] [account-inbox](https://github.com/linagora/esn-frontend-account-inbox)
- [x] [admin](https://github.com/linagora/esn-frontend-admin)
- [x] [videoconference-calendar](https://github.com/linagora/esn-frontend-videoconference-calendar)
- [x] [application-grid](https://github.com/linagora/esn-frontend-application-grid)
- [x] [group](https://github.com/linagora/esn-frontend-group)
- [x] [login](https://github.com/linagora/esn-frontend-login)
- [x] [linshare](https://github.com/linagora/esn-frontend-linshare)

**Comment by oubchid** [comment]
It seems the we need to fix linter issues by upgrading version of eslint-plugin-import

https://github.com/linagora/esn-frontend-contacts/pull/145/files
