### ISSUE TITLE
Update OIDC signinRedirect configuration to remove state params in the url

### ISSUE THREAD

**Issue by fabienmoyon** [linagora/esn-frontend-common-libs#207]
#### CURRENTLY 

With OIDC configuration we have a state params after login into a SPA : 

`http://inbox.open-paas.org.local/inbox/?state=:OIDC STATE PARAMS #/unifiedinbox/inbox`

#### TO DO 

ON OIDC client, update OIDC signinRedirect configuration to remove state params in the url look https://stackoverflow.com/questions/47677639/redirect-after-oidc-client-login

**Comment by alagane** [comment]
Is this bug still present?

I think enabling HTML 5 mode on AngularJS (removing # in urls) fixed it.

**Comment by fabienmoyon** [comment]
Yes we can close it
