### ISSUE TITLE
Can not build applications 

### ISSUE THREAD

**Issue by chamerling** [linagora/esn-frontend-common-libs#43]
The file esn-frontend-common-libs/src/frontend/js/modules/file.js exports an `await` function in `strict` mode:  Uglifying source does not work as is.

Several solutions:

1. Remove strict mode
2. Rename the function and everywhere it is used
3. Find webpack plugins/options

**Comment by MichaelBailly** [comment]
remove strict mode ?

**Comment by chamerling** [comment]
@MichaelBailly doing this just works fine:

![Capture d’écran 2020-07-16 à 17 43 38](https://user-images.githubusercontent.com/264403/87692389-fef3e600-c78b-11ea-89a7-ad63289c1e40.png)

**Comment by chamerling** [comment]
Will go with renaming the function. Removing `use strict` does not work with babel which is also used during the build
