### ISSUE TITLE
[i18n] inject translations

### ISSUE THREAD

**Issue by MichaelBailly** [linagora/esn-frontend-common-libs#58]
Details [here](https://ci.linagora.com/linagora/lgs/openpaas/esn/-/wikis/Frontend-Split/Polish/i18n#code-changes-howto-solution-1-kiss)

**Comment by tuanlc** [comment]
Remember to have this [fix](https://ci.linagora.com/linagora/lgs/openpaas/esn/merge_requests/1275/diffs) for translation
