### ISSUE TITLE
`Promise` will not work on IE

### ISSUE THREAD

**Issue by chamerling** [linagora/esn-frontend-common-libs#64]
There are some recent code which uses `Promise` instead of `$q`. From https://caniuse.com/#feat=promises, this will not work on IE until  we use the Promise polyfill.

There are several solutions:

- Continue to use $q
- Tell webpack that `Promise` is `$q` with `DefinePlugin`
- Use Promise polyfill

**Comment by MichaelBailly** [comment]
I propose to let developers use Promise, and rely on webpack/babel/corejs/... to do the right thing. Please put a :+1: if you agree and :-1: if you don't

**Comment by itswillta** [comment]
Hold on, we still need to support IE? https://github.com/linagora/openpaas-esn/wiki/MVP-environment

**Comment by MichaelBailly** [comment]
no we don't
