### ISSUE TITLE
Bring back missing tests

### ISSUE THREAD

**Issue by itswillta** [linagora/esn-frontend-common-libs#73]
There used to be ***.spec.js** files alongside the JS files. Now I can't find a single one. We need to bring them back.

**Comment by itswillta** [comment]
Needs https://github.com/OpenPaaS-Suite/esn/issues/11.

**Comment by tuanlc** [comment]
> Needs OpenPaaS-Suite/esn#11.

We can do this task by only move the missing spec files first. Make these tests run will be in another ticket.
