### ISSUE TITLE
Makes esnI18nService.translate service work with interpolation

### ISSUE THREAD

**Issue by tuanlc** [linagora/esn-frontend-common-libs#83]
### Context:
To [fix translation](https://ci.linagora.com/linagora/lgs/openpaas/esn/-/wikis/Frontend-Split/Stage-1/i18n) for templates, we [updated translations](https://github.com/OpenPaaS-Suite/esn-frontend-contacts/pull/22/commits/dd92866157be91e51c81e8a6fd86e7935f34cae0) to:

`Address book %s will be deleted along with its contacts.: "Address book {{ addressbookDisplayShell.displayName }} will be deleted along with its contacts."` 

and we [updated template](https://github.com/OpenPaaS-Suite/esn-frontend-contacts/commit/5b7a7b0e07f4b262fb7475f8d57ad0f742508df3) to use: `p {{ 'Address book %s will be deleted along with its contacts.' | translate:$ctrl }}`

To do this, we do not use [i18nInterpolator](https://github.com/OpenPaaS-Suite/esn-frontend-common-libs/blob/main/src/frontend/js/modules/i18n/i18n-interpolator.service.js) that detects `%s` and replace them with proper values.

### Issue
Without `i18nInterpolator`, our syntax  for example `esnI18nService.translate('%s items', $dragData.length);` does not work because translator does not understand `%s` anymore.

We use this syntax in a ton of places in SPAs.

### Solution
Consistent the input of esnI18nService.translate and angular translate filter, the second param (if present) is an object that contains pairs of key + value

- [x] Modify esnI18nService.translate
- [x] Fix in all SPAs to adapt new syntax of the service => Created tickets in other repositories to do this
- [x] Remove the esnI18nInterpolator factory as it is useless now

**Comment by huy-ta** [comment]
Why did we have to update translations to make it work in the PUG templates in the first place?

**Comment by huy-ta** [comment]
To be honest having AngularJS-specific syntax in the translation files is kinda a bad practice imo. That makes every translation file tightly coupled to AngularJS, which is going to be replaced soon.

**Comment by ppppbn** [comment]
At first, we need to update the translation in order to make angular-translate understand things: https://ci.linagora.com/linagora/lgs/openpaas/esn/-/wikis/Frontend-Split/Stage-1/i18n

**Comment by itswillta** [comment]
Suppose we have the following translation object:

```json
{
  "%s items": "{{ length }} items"
}
```

`$translate.instant('%s items', { length })` should work.

In other words, `esnI18nService.translate('%s items', $dragData.length);` needs to become `esnI18nService.translate('%s items', { length: $dragData.length });`. Of course we'll have to modify the `esnI18nService.translate` method accordingly.

And then we'll need to find every place where `esnI18nService.translate` is used and modify it.

Edit: After that remember to remove the `esnI18nInterpolator` factory as it is useless now.
