### ISSUE TITLE
Flash of untranslated "Application is loading..." text

### ISSUE THREAD

**Issue by itswillta** [linagora/esn-frontend-common-libs#86]
#### How to reproduce

- Change your language to something other than English.
- Reload your SPA (F5).
- You can see that the `Application is loading...` text is displayed in English and then after a few seconds it flashes to your selected language.

#### Suggested solution

We can have a loading effect together with the SPA's icon, and there'll be no need for the `Application is loading...` text anymore.

**Comment by pbson** [comment]
@huy-ta What about a loading effect only, since it's not taking too long for the user attention ( more than 10 seconds according to this: https://www.nngroup.com/articles/response-times-3-important-limits/ ), I don't think we need anything for explanation ?
